### ISSUE TITLE
when there are updates SOGo

### ISSUE THREAD

**Issue by MisterM74** [cmjnisse/sogo-ispconfig#20]
Hello
When the features are updated SOGo side also added them in yours?

Best Regards

MZ

**Comment by cmjnisse** [comment]
well i just (to day) started up again with this project, so once i locate all the new configuration variables i will add them to admin section.
if you are missing configuration variables just post them here and i will focus on adding them first

in the mean time you can use the custom section and add new settings that are missing, like this

    <key>Configuration_Name</key>
    <string>int or string</string>
    # OR #
    <array>
    <string>int or string</string>
    <string>int or string</string>
    </array>

etc...

**Comment by MisterM74** [comment]
ok thank you

**Comment by MisterM74** [comment]
I forgot one thing.
At a SOGo update of, is it possible to see if there a configuration list that was to say?
Yours
Mz

**Comment by mehargags** [comment]
I'm a little confused here.
Can you let me know if the current available version or your script will work in Latest sable ISPConfig 3xxp5 or not ?

**Comment by MisterM74** [comment]
The latest version of ISPConfig
works nickel
Follow the tutorial is indicated for installation
https://github.com/cmjnisse/sogo-ispconfig/wiki/Install-Latest
Many greetings
Mz
