### ISSUE TITLE
If I use Jessie (Debian Package)

### ISSUE THREAD

**Issue by MisterM74** [cmjnisse/sogo-ispconfig#21]
hello
Knowing that your setup file is not current with Debian 8, I wonder if I can use it as well, or else, you will have to wait for the update?
Many greetings
Mz

**Comment by cmjnisse** [comment]
So far my test says YES,

but you have to check that the configuration files in `/usr/local/ispconfig/server/lib/config.inc.local.php` are correct debian package uses `sogod.plist` just like ubuntu

```
$conf['sogo_gnu_step_defaults']
$conf['sogo_gnu_step_defaults_sogod.plist']
```

before install change [_ins/Installer.php:462](https://github.com/cmjnisse/sogo-ispconfig/blob/master/_ins/Installer.php#L462) the current default setting is **WRONG** `{SOGOHOMEDIR}/var/lib/sogo/GNUstep/Defaults/sogod.plist` **it should be** `{SOGOHOMEDIR}/GNUstep/Defaults/sogod.plist`

**Comment by MisterM74** [comment]
The version of ubuntu, which?

**Comment by cmjnisse** [comment]
can't remember which version of ubuntu that started but it in the newer version.
simple rule after configuration of sogo if file `sogod.plist` exists that's where the changes needs to be written

**Comment by MisterM74** [comment]
even choosing Ubuntu Trusty (14.04 LTS), I display an error message and am white but in the rest of the installation, as follows:
Updating apt package list
Reading package lists...
About to install SOGo
Shall i install sogo-activesync? (Y/N) [Y]: Y
E: Unable to correct problems, you have held broken packages.
 sogo : Depends: libmemcached10 but it is not installablememcached not happy w. IPv6, setting to 127.0.0.1

ALL DONE.. SOGo is now installed on your server..!

location of SOGo init script []:
MZ

**Comment by cmjnisse** [comment]
i can replecate that

whats in your source.list file

**Comment by MisterM74** [comment]
drops, I passed in Trusty, we can close the subject, thank you as well for your help
Mz
