### ISSUE TITLE
if I use an older version

### ISSUE THREAD

**Issue by MisterM74** [cmjnisse/sogo-ispconfig#22]
hello
I use Ubuntu 14.10 LTS.
Logically packets stops at the 14.04 release.
if I use the packets of the 14.04 release, is this going to work?
IN until the Yearly Disposable either create?
Many greetings
thank you
MZ

**Comment by cmjnisse** [comment]
SOGo packages for Ubuntu are for the extended support release https://wiki.ubuntu.com/LTS
you can try installing Debian packages, i don't recommend that but it works sometimes, else you can build SOGo from source using the official repository

**Comment by MisterM74** [comment]
recompile sources, you have an idea as is.
I know that is moving, but here ...
thank you

**Comment by cmjnisse** [comment]
Not tested but this is how would rebuild the package
add `http://inverse.ca/ubuntu trusty trusty` repository to your source.list
```
apt-get update
cd /usr/src/
apt-get source sogo 
apt-get build-dep sogo
cd sogo*

```
then rebuild the package
```
# USE one of these commands not both
debuild -us -uc
OR
dpkg-buildpackage -rfakeroot -D -us -uc
```

this way you build the original package against the package versions on your system from your previous post in https://github.com/cmjnisse/sogo-ispconfig/issues/21#issuecomment-98990778 `libmemcached10` is now `libmemcached11` or what ever version is available

once the build is done install the new .deb packages and resolve any missing package one by one, it's a pain to do it like this and makes updating SOGo an task all by it self.
```
cd ../
dpkg -i  sogo-activesync*.deb	 sogo_2.2.*.deb
```

**Comment by MisterM74** [comment]
I have this message when I try to compile the package.

dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: source package sogo
dpkg-buildpackage: source version 2.2.17a-1
dpkg-buildpackage: source distribution trusty
dpkg-buildpackage: source changed by Inverse Support <support@inverse.ca>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build sogo-2.2.17a
dpkg-checkbuilddeps: Unmet build dependencies: libsope-appserver4.9-dev libsope-core4.9-dev libsope-gdl1-4.9-dev libsope-ldap4.9-dev libsope-mime4.9-dev libsope-xml4.9-dev libsbjson-dev
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)

Mz

**Comment by MisterM74** [comment]
hi
This also
apt-get build-dep sogo
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages have unmet dependencies:
 libsbjson-dev : Depends: libsbjson2.3 (= 2.3.2-2+b1) but 4.9.r1664.20150326 is to be installed
E: Build-dependencies for sogo could not be satisfied.

Mz

**Comment by cmjnisse** [comment]
than you can edit the control file to match the versions available and download the packages individually or not use SOGo on that OS version.

sorry but if it's not simple to compile using apt-get then it's not a question that belongs here, but a question that belongs on an forum where people specializes in compiling from source

**Comment by MisterM74** [comment]
My friend after successfully compiles, I file this as:
sogo_2.2.17a-1_amd64.deb
sogo-activesync_2.2.17a-1_amd64.deb
sogo-dbg_2.2.17a-1_amd64.deb
sogo-dev_2.2.17a-1_amd64.deb
sogo-openchange_2.2.17a-1_amd64.deb

I miss that file so that sogo or in connection with mysql, any idea?
sope4.9-gdl1-mysql

Mz

**Comment by cmjnisse** [comment]
sope and sogo isn't the same, they are two different package if your cant install sope using apt-get you will need to compile sope from source also

**Comment by MisterM74** [comment]
I am trying to recompile sope
The library and the same as MariaDB mysql libraries?
Yours
Mz

**Comment by MisterM74** [comment]
Hi

In addition to packet sogo I Sope packages:

sope4.9-dbg_4.9.r1664.20150326_amd64.deb
libsope4.9-dev_4.9.r1664.20150326_all.deb
libsope-appserver4.9-dev_4.9.r1664.20150326_amd64.deb
libsope-appserver4.9_4.9.r1664.20150326_amd64.deb
sope4.9-appserver_4.9.r1664.20150326_amd64.deb
libsope-core4.9-dev_4.9.r1664.20150326_amd64.deb
libsope-core4.9_4.9.r1664.20150326_amd64.deb
libsope-xml4.9-dev_4.9.r1664.20150326_amd64.deb
libsope-xml4.9_4.9.r1664.20150326_amd64.deb
libsope-ldap4.9-dev_4.9.r1664.20150326_amd64.deb
libsope-ldap4.9_4.9.r1664.20150326_amd64.deb
libsope-mime4.9-dev_4.9.r1664.20150326_amd64.deb
libsope-mime4.9_4.9.r1664.20150326_amd64.deb
libsope-gdl1-4.9-dev_4.9.r1664.20150326_amd64.deb
libsope-gdl1-4.9_4.9.r1664.20150326_amd64.deb
sope4.9-gdl1-postgresql_4.9.r1664.20150326_amd64.deb
sope4.9-gdl1-mysql_4.9.r1664.20150326_amd64.deb
sope4.9-stxsaxdriver_4.9.r1664.20150326_amd64.deb
sope4.9-libxmlsaxdriver_4.9.r1664.20150326_amd64.deb
libsbjson2.3_4.9.r1664.20150326_amd64.deb
libsbjson2.3-dev_4.9.r1664.20150326_amd64.deb

the thing you forget in the first message, an additional function:

dpkg-buildpackage -rfakeroot -D -us -uc -d

Thank you for your help
Mz

**Comment by MisterM74** [comment]
One idea is to compile and install SOPE
 sogo-activesync : Depends: sogo (= 2.2.17a-1) but it is not going to be installed.
                   Depends: libsope1 (>= 2.2.9) but it is not going to be installed.

MZ

**Comment by MisterM74** [comment]
hi
This mistake, you already had?
object not found: SOGo => index
thank you
Mz

**Comment by MisterM74** [comment]
Hi
Found my friend
How, simple, compile the wheezy version Jessie and presto, it works and config you proposed at the first message.
Yours
Mz

**Comment by cmjnisse** [comment]
hi

sorry for the late reply.
glad you worked it out.
`object not found: SOGo => index` i have no idea what that means or how to fix it
