### ISSUE TITLE
Updating the base

### ISSUE THREAD

**Issue by MisterM74** [cmjnisse/sogo-ispconfig#26]
hello
Knowing that SOGo happened in 2.3.0 and I think, I'm not sure, but there it to you an update on the new version?

Because if I run this:

/usr/share/doc/sogo/sql-update-2.2.17_to_2.3.0.sh

This venture stop working?

thank you

Mz

**Comment by cmjnisse** [comment]
not sure what you mean!
what is not working?, i upgraded SOGo on my production servers monday night and i haven't had an error yet
just now, i upgraded all files related to this plugin from master and it's still working, so i need more details on what error(s) you experience

that script is for SOGo auto created tables and not the users table.

**Comment by MisterM74** [comment]
Did you not understand?
I paused the question to the comunity SOGo about this:

Jun 02 15:05:20 sogod [25593]: <0x0x7f2a523b4cf0[NGImap4Client]> Note: no key found for sorting, using 'DATE': (null)
Jun 02 15:05:21 sogod [25593]: <0x0x7f2a523b4cf0[NGImap4Client]> Note: no key found for sorting, using 'DATE': (null)
Jun 02 15:05:21 sogod [25593]: <0x0x7f2a523b4cf0[NGImap4Client]> Note: no key found for sorting, using 'DATE': (null)
Jun 02 15:05:22 sogod [25593]: <0x0x7f2a523b4cf0[NGImap4Client]> Note: no key found for sorting, using 'DATE': (null)
Jun 02 15:05:22 sogod [25593]: <0x0x7f2a523b4cf0[NGImap4Client]> Note: no key found for sorting, using 'DATE': (null)
Jun 02 15:05:23 sogod [25593]: <0x0x7f2a523b4cf0[NGImap4Client]> Note: no key found for sorting, using 'DATE': (null)
Jun 02 15:05:23 sogod [25593]: <0x0x7f2a523b4cf0[NGImap4Client]> Note: no key found for sorting, using 'DATE': (null)
Jun 02 15:05:24 sogod [25593]: <0x0x7f2a523b4cf0[NGImap4Client]> Note: no key found for sorting, using 'DATE': (null)
Jun 02 15:05:25 sogod [25593]: <0x0x7f2a523b4cf0[NGImap4Client]> Note: no key found for sorting, using 'DATE': (null)

And I replied that he just had to perform an update of the tables, with the file I noted.

thank you to enlighten me

Mz

**Comment by cmjnisse** [comment]
this warning is related to SOGo and not this addon, 
therefore i am closing it as off topic
