### ISSUE TITLE
[question] How about ISPConfig 3.0.5.4p8?

### ISSUE THREAD

**Issue by JustDevZero** [cmjnisse/sogo-ispconfig#27]
Hi,

One week ago ISPConfig 3.0.5.4p8 was realed which included some little patch.

In your README.md mentions 3.0.4.5p3, which is indeed pretty old. Usually developers (I include my self), are a bit lazy updating the readmes.

So my question is basically, How about ISPConfig 3.0.5.4p8? It will work, or maybe If I not try in production?

Thanks for all.

**Comment by cmjnisse** [comment]
For me yes.
I update ISPConfig yesterday by mistake (so tired at the time) wrong server i logged into.

how ever if you have a busy SOGo server mainly with ActiveSync, then after reconfiguration of SOGo the processes may not have let completely go of the socket it binds to, and then fail to bind on the same socket again

other than that i don't have any issues

**Comment by JustDevZero** [comment]
"Luckly" the SOGO server is not yet installed, well, postfix and stuff yes, but now working as SOGo, indeed, I was watching your repo because I want to try SOGo with ISPConfig, for first time.

So I'll try it tonight with one of my servers, of course previous backup.

**Comment by cmjnisse** [comment]
Your welcome
if you have any suggestions, improvement or anything just write them here and i'll look into it

**Comment by JustDevZero** [comment]
Everything is apparently working on debian installations...

But I see no compatibility with CentOS (my main mail servers are CentOS) :/

Before continue on our production... I think I wil need to patch/contribute with the code ;)

Afaik, correct me if I'm wrong, sogo-ispconfig can work with multiple servers separared, right? (I have every service in different machines)

**Comment by cmjnisse** [comment]
> Correct me if I'm wrong, sogo-ispconfig can work with multiple servers separared, right? (I have
> every service in different machines)

Yes, but if SOGo is installed on a machines without mail service you must make sure 'remote actions' are supported by the ISPConfig version on that server, i'm not sure exactly when that feature were introduced but should be from version 3.0.5 and up

> Afaik, it looks is not adapted to be used with CentOS (my main mail servers are CentOS/RHL) :/

Sorry, but testing on three different operation system is not currently an option for me
_if i remember correctly, you just need to skip install and do it manually_

**Comment by JustDevZero** [comment]
Ok, works with the newer version of ispconfig.

But now I've got other problems, I opened #30 to not mess with this.
