### ISSUE TITLE
bug add E-mail adress

### ISSUE THREAD

**Issue by MisterM74** [cmjnisse/sogo-ispconfig#37]
Hello
I carry perform the update package
And since then, I do not remember adding an email address to Sogo, here the error below I:

SOGo Sync Mail Users - Unable to fetch the domain config for domain [domain.com]

Thanks for your help
Mz

**Comment by cmjnisse** [comment]
whats your module settings?
and did you use testing or master branch?

**Comment by MisterM74** [comment]
and did you use testing or master branch?

I did not understand the answer

https://github.com/cmjnisse/sogo-ispconfig

But I found this error message you post

https://github.com/cmjnisse/sogo-ispconfig/blob/master/docs/Errors.txt

sogo_plugin::__sync_mail_users(): unable to fetch the domain config for domain [example.dk]
	* when this error is raised and logged, it means the you DO NOT have configuration that can be used with this domain
	* this is usually followed by a warning (NOT AN ERROR) from "sogo_helper::get_domain_config()

Does that answer your question

unable to fetch the domain config for domain [example.dk]

I have to perform any operation that I can add users and so that it can connect to this SOGo because at the moment I do not know ..

Thank you

Mz

**Comment by MisterM74** [comment]
I give a simple comment to say that the update does not work, and I had to reinstall all, here

**Comment by cmjnisse** [comment]
ok. i assume you used the master branch. (branch = here at GitHub)

what version did you update from?

the message is simple that it were not able to lookup the configuration to use when creating the configuration, therefore i asked what your module settings were ("System => SOGo => Settings"), they define how the script lookup the configuration to use

**Comment by MisterM74** [comment]
Let's say the last, which is why I left the error message at the beginning of the topic ...
if you still includes a time my sentence ...

Michel
