### ISSUE TITLE
Connection error Mail (El Capitan)

### ISSUE THREAD

**Issue by MisterM74** [cmjnisse/sogo-ispconfig#40]
Hello
 

Hey hey, I went to El Capitan, and since this version with apple on email that's EAS log on, but I have this error when I log:
 

Sep 14 18:49:34 sogod [16026]: <0x0x7fe0016cdde8[SOGoActiveSyncDispatcher]> EAS - Forbidden access for user (null)
Sep 14 18:49:34 sogod [16026]: localhost.localdomain "POST /SOGo/Microsoft-Server-ActiveSync HTTP/1.1" 403 0/612 0.002 - - 0
 

Did I forget something in my config apache2
 

Many greetings
 

Michel

**Comment by cmjnisse** [comment]
i no longer develop on this, so don't know.

**Comment by MisterM74** [comment]
you stop the development of Sogo ISPConfig?
